# Generated by Django 5.1.3 on 2024-11-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kutubxonachi',
            options={'verbose_name': 'Kutubxonachi', 'verbose_name_plural': 'Kutubxonachilar'},
        ),
    ]
